server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ithan2422331/shop-config.git
          default-label: master
          search-paths: blog-config
